### ISSUE TITLE
Prevent dragging of nodes

### ISSUE THREAD

**Issue by anirudhsama** [zakjan/pixi-graph#11]
Is there any way to prevent a node from being dragged? I plan to use this in a game and I don't want players to move around the nodes.

**Comment by zakjan** [comment]
Hi, I'm sorry but such feature is currently not there. It's planned, but unfortunately I'm occupied on other projects so I can't provide an estimate when it could be implemented. For a production use, you would probably be better with for example recently released [Sigma v2](https://twitter.com/sigmajs/status/1450480807244701699).

**Comment by maccman** [comment]
This would be useful to us too.
