### ISSUE TITLE
Graph with 0 nodes does not display nodes when added

### ISSUE THREAD

**Issue by NHAS** [zakjan/pixi-graph#19]
Hi there, thanks for this project its really useful for me! 

I think my problem comes from the following code:
```js
  private createGraph() {
    this.graph.forEachNode(this.createNode.bind(this));
    this.graph.forEachEdge(this.createEdge.bind(this));
  }
```

Effectively if you start a new pixi-graph with 0 nodes and 0 edges, the new node/edge handler is never bound thus if you then create a new node in the graph it does not get rendered.

To be fair, Im quite new at JS, and I dont think this is the full picture as even if I add two dummy nodes, then immediately remove them then it still fails to render anything.

**Comment by zakjan** [comment]
Hi, I'm archiving this repository as read-only because of lack of capacity to maintain it. Feel free to continue in your own fork.
