### ISSUE TITLE
Non WebGL support

### ISSUE THREAD

**Issue by maccman** [zakjan/pixi-graph#3]
Currently non webgl browsers fail to load pixi-graph. We have a small fork to pixi graph that fixes that. Would you like to see this upstream?

https://github.com/team-reflect/pixi-graph/commit/fb57114f274eb377e66d783775e6e08e17e3e2c7

**Comment by zakjan** [comment]
Hi Alex, pixi.js package contains WebGL renderer only. Supporting non-WebGL browsers is possible with pixi.js-legacy instead.

FAIL_IF_MAJOR_PERFORMANCE_CAVEAT is a WebGL flag. Setting it to false helps for example if WebGL runs with CPU emulation in remote desktop environments.

https://pixijs.download/dev/docs/PIXI.settings.html#FAIL_IF_MAJOR_PERFORMANCE_CAVEAT

I have a branch to upgrade pixi.js to v6. This flag is false there by default. Also, I'm going to move pixi.js from peer dependencies to normal dependencies. Would this change work for you?

**Comment by maccman** [comment]
Yup, sound great!

cc @laszlolm

**Comment by maccman** [comment]
Yup, sound great!

cc @laszlolm

**Comment by laszlolm** [comment]
Please notify me once this is merged @zakjan so we can swap out our fork to this package again

**Comment by zakjan** [comment]
@laszlolm Released as 1.3.0. The only change is the update to Pixi v6 (using separate Pixi packages as regular dependencies, instead of previously used Pixi bundle as peer dependency). Let me know how it works for you.

**Comment by zakjan** [comment]
For browsers with no WebGL support, I'll need to create a separate bundle including @pixi/canvas. Is it still required for your usecase, or is FAIL_IF_MAJOR_PERFORMANCE_CAVEAT = false good enough for you?
