### ISSUE TITLE
scale bug

### ISSUE THREAD

**Issue by zszq** [zakjan/pixi-graph#8]
After the view is zoomed out to the point where the line disappears, drag the point, and then zoom in, the line will not be displayed.

**Comment by zakjan** [comment]
Thanks for reporting, I can reproduce it. Are you able to find out the cause, and send a PR?

**Comment by zakjan** [comment]
Hi, I'm archiving this repository as read-only because of lack of capacity to maintain it. Feel free to continue in your own fork.
